# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: Set managed_platform
  ansible.builtin.set_fact:
    managed_platform: "{{ 'api.mpp' in host }}"
  tags:
    - always

- name: Set with_sandbox
  ansible.builtin.set_fact:
    with_sandbox: "{{ service == 'packit' }}"
  tags:
    - always

- name: Set sandbox_namespace
  when: with_sandbox
  tags:
    - always
  block:
    - name: Set sandbox_namespace (MP+)
      ansible.builtin.set_fact:
        sandbox_namespace: "{{ tenant }}--{{ deployment }}-sandbox"
      when: managed_platform
    - name: Set sandbox_namespace
      ansible.builtin.set_fact:
        sandbox_namespace: "{{ service }}-{{ deployment }}-sandbox"
      when: not managed_platform

- name: Set servicephase
  when: managed_platform
  tags:
    - always
  block:
    - name: Set servicephase for staging
      ansible.builtin.set_fact:
        servicephase: preprod
      when: deployment == "stg"
    - name: Set servicephase for production
      ansible.builtin.set_fact:
        servicephase: prod
      when: deployment == "prod"

- name: Set Redis-like hostname
  tags:
    - always
  ansible.builtin.set_fact:
    redis_hostname: "{{ kv_database }}"

- name: Set Bitwarden URI
  tags:
    - always
  ansible.builtin.set_fact:
    bw_uri: "ansible://{{ service }}/{{ deployment }}"

- name: Fetch git forges
  when: deployment != "dev"
  tags:
    - always
  ansible.builtin.set_fact:
    git_forges: "{{ lookup('community.general.bitwarden', bw_uri + '/git', search='') }}"
