# Copyright Contributors to the Packit project.
# SPDX-License-Identifier: MIT

---
- name: Install Python cryptography module
  package:
    name:
      - python-cryptography
  become: true

- name: Generate OpenSSL private keys
  openssl_privatekey:
    path: "{{ path_to_secrets }}/{{ item }}"
  loop:
    - private-key.pem
    - privkey.pem
    - centos-server-ca.cert
    - centos.cert

- name: Generate OpenSSL CSR
  openssl_csr:
    path: "{{ path_to_secrets }}/{{ item.csr }}"
    privatekey_path: "{{ path_to_secrets }}/{{ item.key }}"
    common_name: "{{ server_hostname }}"
  loop:
    - { key: privkey.pem, csr: fullchain.csr }

- name: Generate Self Signed OpenSSL certificate
  openssl_certificate:
    path: "{{ path_to_secrets }}/{{ item.cert }}"
    privatekey_path: "{{ path_to_secrets }}/{{ item.key }}"
    csr_path: "{{ path_to_secrets }}/{{ item.csr }}"
    provider: selfsigned
  loop:
    - { cert: fullchain.pem, key: privkey.pem, csr: fullchain.csr }

- name: Remove CSR
  file:
    path: "{{ path_to_secrets }}/{{ item }}"
    state: absent
  loop:
    - fullchain.csr
